version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379

  # pgAdmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   restart: always
  #   ports:
  #     - 15432:80
  #   environment:
  #     - PGADMIN_DEFAULT_PASSWORD=ignite
  #     - PGADMIN_DEFAULT_EMAIL=postgres@email.com
  #   links: 
  #     - database_ignite
  #   depends_on:
  #     - database_ignite


  # app:
  #   build: .
  #   container_name: rentx
  #   restart: always
  #   ports: 
  #     - 3333:3333
  #     - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
  #   volumes: 
  #     - .:/usr/app
  #   links: 
  #     - database_ignite
  #   depends_on:
  #     - database_ignite

volumes:
  pgdata:
    driver: local